import { useEffect, useRef } from 'react'
import { observer } from 'mobx-react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dataStore from '../stores/dataStore'

const Home: NextPage = observer(() => {
  const socket = useRef<WebSocket>()

  const connect = () => {
    if (typeof window !== 'undefined') {
      socket.current = new WebSocket("wss://www.cryptofacilities.com/ws/v1")
      socket.current.onopen = function(e) {
        socket.current?.send('{"event":"subscribe","feed":"book_ui_1","product_ids":["PI_XBTUSD"]}');
      };
      socket.current.onmessage = function(event) {
        if(event.data) {
          const data = JSON.parse(event.data)
          if (data.feed === 'book_ui_1_snapshot') {
            console.log('yest', data)
            dataStore.setData(data)
          }
        }
      };
      socket.current.onclose = function(event) {
        if (event.wasClean) {
          console.log('cleanClose')
        } else {
          console.log('notcleanClose')
          // e.g. server process killed or network down
          // event.code is usually 1006 in this case

        }
      };
      socket.current.onerror = function(error) {
        console.log('error')
      };
    }
  }
  const toggleFeed = () => {
    if (typeof window !== 'undefined' && socket.current) {
      if(socket.current.readyState === 1) {
        console.log('socket is OPEN!')
        socket.current.close()
      }
      else {
        connect()
      }
    }
  }

  const handleVisibilityChange = () => {
    if (document.visibilityState === "hidden" && socket.current) {
      console.log('stop')
      socket.current.close()
    } else  {
      console.log('Allow start')
    }
  }

  useEffect(() => {
    connect()
    document.addEventListener("visibilitychange", handleVisibilityChange, false);
  },[])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
        </h1>

        <div className={styles.grid}>
          <button onClick={toggleFeed}>
          Refresh the feed
          </button>
        </div>
        {dataStore?.asks[0] && dataStore?.bids[0] &&  (
        <table>
        <tbody>
          <tr>
            <th>Total</th>
            <th>Size</th>
            <th>Price</th>
            <th>Price</th>
            <th>Size</th>
            <th>Total</th>
          </tr>
          <tr>
            <th>{dataStore.asks[0][2]}</th>
            <th>{dataStore.asks[0][1]}</th>
            <th>{dataStore.asks[0][0]}</th>
            <th>{dataStore.bids[0][0]}</th>
            <th>{dataStore.bids[0][1]}</th>
            <th>{dataStore.bids[0][2]}</th>
          </tr>
        </tbody>
      </table>
        )}
        <div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
})

export default Home
